---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno-policies
  namespace: uc2-openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/nasx/acm-kyverno-example.git
        revision: HEAD
        directories:
          - path: kyverno-policies/uc2-app
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
      labels:
        velero.io/exclude-from-backup: 'true'
      name: 'kyverno-policies-{{.path.basename}}'
    spec:
      destination:
        namespace: uc2-openshift-gitops
        server: https://kubernetes.default.svc
      project: default
      sources:
        - path: '{{.path.path}}'
          repoURL: https://github.com/nasx/acm-kyverno-example.git
          targetRevision: HEAD
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=false