---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: hub-gitops
placementBindingDefaults:
  name: hub-gitops
policies:
  - manifests:
    - path: manifests/applicationset.yaml
    name: hub-gitops-bootstrap
policyDefaults:
  categories:
    - CM Configuration Management
  complianceType: musthave
  configurationPolicyAnnotations:
    policy.open-cluster-management.io/disable-templates: 'true'
  controls:
    - CM-2 Baseline Configuration
  namespace: open-cluster-management-global-set
  remediationAction: enforce
  severity: high
  standards:
    - NIST SP 800-53
policySets:
  - description: Security Specific Policies for All OpenShift Clusters
    name: hub-gitops
    placement:
      placementPath: hub-placement.yaml
    policies:
      - hub-gitops-bootstrap
