---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: patches/placement.yaml
    target:
      group: cluster.open-cluster-management.io
      kind: Placement
      name: kyverno-openshift-appset-placement
      version: v1beta1
resources:
  - ../../base
