---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: patches/applicationset.yaml
    target:
      group: argoproj.io
      kind: ApplicationSet
      name: kyverno
      version: v1alpha1
  - path: patches/placement.yaml
    target:
      group: cluster.open-cluster-management.io
      kind: Placement
      name: kyverno-placement
      version: v1beta1
resources:
  - ../../base
