---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: kyverno-openshift-appset-placement
  namespace: uc2-openshift-gitops
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: policysets/baseline-security
              operator: Exists
