---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: kyverno-policies-uc2-app
placementBindingDefaults:
  name: kyverno-policies-uc2-app
policies:
  - name: uc2-app-kyverno-policies
    manifests:
      - path: manifests/uc2-app-namespace-require-labels.yaml
policyDefaults:
  categories:
    - CM Configuration Management
  complianceType: musthave
  copyPolicyMetadata: false
  configurationPolicyAnnotations:
    policy.open-cluster-management.io/disable-templates: 'true'
  controls:
    - CM-2 Baseline Configuration
  informKyvernoPolicies: false
  namespace: open-cluster-management-global-set
  placement:
    placementPath: uc2-app-placement.yaml
  remediationAction: enforce
  severity: high
  standards:
    - NIST SP 800-53
