---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: kyverno-policies-uc2-app-placement
  namespace: open-cluster-management-global-set
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: uc2-app
              operator: Exists
